name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Debug Environment
        run: |
          echo "Checking environment setup..."
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Checking if .env file will be created..."

      - name: Create env file
        run: |
          touch .env
          echo "REACT_APP_TOGETHER_API_KEY=${{ secrets.REACT_APP_TOGETHER_API_KEY }}" >> .env
          echo "Env file created successfully"
          echo "Checking if API key is set (length only):"
          echo "API key length: ${#REACT_APP_TOGETHER_API_KEY}"

      - name: Install Dependencies
        run: |
          npm install
          echo "Dependencies installed successfully"

      - name: Build
        run: |
          echo "Starting build process..."
          npm run build
          echo "Build completed successfully"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build